# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService

end

target 'push_notification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for push_notification
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
end
